apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "check-mk.fullname" . }}
  labels:
    app: {{ template "check-mk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "check-mk.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "check-mk.name" . }}
    spec:
      containers:
      - name: promonitor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: TZ
            value: "{{ .Values.checkmk.timezone }}"
          - name: CMK_SITE_ID
            value: "{{ .Values.checkmk.siteName }}"
          - name: CMK_LIVESTATUS_TCP
            value: "on"
          - name: CMK_MAIL_RELAYHOST
            value: "{{ .Values.checkmk.mailRelayHost }}"
          - name: CMK_SITE_USER
            value: "{{ .Values.checkmk.siteUser }}"
          - name: CMK_SITE_PASSWORD
            value: "{{ .Values.checkmk.sitePassword }}"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
        ports:
        {{- range $name, $svc := .Values.service }}
        {{ if $svc.enabled }}
        - containerPort: {{ $svc.internalPort }}
          name: {{ $name }}
          protocol: TCP
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- range $key, $value := .Values.persistence }}
        {{- if not $value.existingClaim }}
        - name: {{ template "check-mk.name" $ }}-{{ $key }}
          mountPath: {{ $value.mountPath }}
        {{- end }}
        {{- end }}
      volumes:
      {{- range $key, $value := .Values.persistence }}
      {{- if not $value.existingClaim }}
        - name: {{ template "check-mk.name" $ }}-{{ $key }}
          persistentVolumeClaim:
            claimName: {{ template "check-mk.name" $ }}-{{ $key }}
      {{- end }}
      {{- end }}
        - name: {{ template "check-mk.name" $ }}-tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.tmpfs.size }}
